import type { EditableStory } from "../lib/site-content";
import { categoryMatchesLabel } from "./sections";

export type ClubProfile = {
  title: string;
  location: string;
  country: string;
  founded?: string;
  website?: {
    label: string;
    url: string;
    host: string;
  };
  address?: string;
  email?: string;
  telephone?: string;
  mapQuery: string;
  setting: string;
  knownFor: string;
  sailing: string;
  facilities: string;
  visitors: string;
};

export const clubProfiles: Record<string, ClubProfile> = {
  "clubs-edgartown-yacht-club-eyc": {
    title: "Edgartown Yacht Club (EYC)",
    location: "Edgartown, Martha's Vineyard, Massachusetts",
    country: "United States",
    founded: "1905",
    website: { label: "Edgartown Yacht Club", url: "https://www.edgartownyc.org/", host: "edgartownyc.org" },
    address: "1 Dock Street, Edgartown, Massachusetts, 02539",
    email: "office@edgartownyc.org",
    telephone: "+1 (508) 627-4361",
    mapQuery: "Edgartown Yacht Club, Edgartown, Massachusetts",
    setting: "a classic New England harbour club on Martha's Vineyard, with moorings, launch traffic, summer fleets and a strong island sailing rhythm.",
    knownFor: "its long-established regatta culture, harbour racing and the traditional summer yacht-club scene around Edgartown.",
    sailing: "Racing and junior sailing sit at the heart of the club, with keelboat and one-design activity shaped by tidal water, summer breeze and busy harbour approaches.",
    facilities: "The club operates as a harbour clubhouse and sailing base, with member facilities, launch access and waterside services for racing and cruising sailors.",
    visitors: "Visiting sailors should treat Edgartown as a popular seasonal harbour: plan ahead, check local mooring arrangements and expect a lively summer waterfront.",
  },
  "clubs-island-sailing-club-isc": {
    title: "Island Sailing Club (ISC)",
    location: "Cowes, Isle of Wight",
    country: "United Kingdom",
    founded: "1889",
    website: { label: "Island Sailing Club", url: "https://www.islandsc.org.uk/", host: "islandsc.org.uk" },
    mapQuery: "Island Sailing Club, Cowes, Isle of Wight",
    setting: "a Cowes waterfront club looking straight into one of the busiest and most storied sailing waters in Britain.",
    knownFor: "the Round the Island Race, Solent racing and the sort of club life that keeps Cowes noisy in the best possible way.",
    sailing: "The club is closely tied to Solent racing, handicap fleets, regatta starts and the annual challenge of getting cleanly around the Isle of Wight.",
    facilities: "Its Cowes base gives members and visitors easy access to race management, waterfront hospitality and the wider town marina network.",
    visitors: "For visiting crews, Cowes offers berths, yards, chandleries and more sailing conversation than most sensible people can digest in one evening.",
  },
  "clubs-balboa-yacht-club-byc": {
    title: "Balboa Yacht Club (BYC)",
    location: "Newport Beach, California",
    country: "United States",
    founded: "1922",
    website: { label: "Balboa Yacht Club", url: "https://www.balboayachtclub.com/", host: "balboayachtclub.com" },
    mapQuery: "Balboa Yacht Club, Newport Beach, California",
    setting: "a Southern California yacht club based in Newport Harbor, with protected water inside and the Pacific waiting outside.",
    knownFor: "junior sailing, harbour racing and a steady connection with offshore-minded West Coast sailors.",
    sailing: "Balboa's sailing programme draws on Newport Harbor's mix of dinghy work, keelboat racing and coastal passages beyond the harbour entrance.",
    facilities: "The clubhouse and harbour setting support member dining, sailing events, guest activity and access to the wider Newport marine trade.",
    visitors: "Visiting crews should expect a busy harbour, polished yacht-club manners and plenty of local knowledge on tides, traffic and berthing.",
  },
  "clubs-chicago-yacht-club-cyc": {
    title: "Chicago Yacht Club (CYC)",
    location: "Chicago, Illinois",
    country: "United States",
    founded: "1875",
    website: { label: "Chicago Yacht Club", url: "https://www.chicagoyachtclub.org/", host: "chicagoyachtclub.org" },
    mapQuery: "Chicago Yacht Club, Chicago, Illinois",
    setting: "a major Great Lakes club with Lake Michigan on the doorstep and Chicago's skyline as its unmistakable backcloth.",
    knownFor: "the Chicago Yacht Club Race to Mackinac, one-design fleets and a strong Great Lakes racing tradition.",
    sailing: "The club's sailing calendar ranges from junior work and buoy racing to distance racing where lake weather can make fools of lazy forecasts.",
    facilities: "City-front clubhouse facilities, race organisation and access to Chicago harbour services make it a serious base for sailors and owners.",
    visitors: "Visiting yachts should plan around Lake Michigan weather, harbour reservations and the simple fact that Chicago gets busy when the season is on.",
  },
  "clubs-club-nautico-santa-pola": {
    title: "Club Nautico Santa Pola",
    location: "Santa Pola, Alicante",
    country: "Spain",
    website: { label: "Club Nautico Santa Pola", url: "https://www.cnsantapola.com/", host: "cnsantapola.com" },
    mapQuery: "Club Nautico Santa Pola, Alicante, Spain",
    setting: "a Mediterranean club and marina base on Spain's Costa Blanca, close to the waters between Santa Pola and Tabarca.",
    knownFor: "local sailing, cruising access, dinghy activity and a practical marina setting for the Alicante coast.",
    sailing: "The sailing is shaped by Mediterranean sea breeze, coastal passages and club racing suited to crews who like sunshine with their tactics.",
    facilities: "Marina services, clubhouse facilities and local marine trades support cruising boats, racing crews and visiting yachts.",
    visitors: "Visitors should check berth availability and approach details in advance, especially during holiday periods and local events.",
  },
  "clubs-clube-naval-de-cascais-cnc": {
    title: "Clube Naval de Cascais (CNC)",
    location: "Cascais",
    country: "Portugal",
    founded: "1938",
    website: { label: "Clube Naval de Cascais", url: "https://www.cncascais.com/", host: "cncascais.com" },
    mapQuery: "Clube Naval de Cascais, Cascais, Portugal",
    setting: "a Portuguese Atlantic club based in Cascais, where Lisbon's sailing scene meets open-water breeze and swell.",
    knownFor: "international regattas, Olympic-class sailing and its position on a handsome Atlantic waterfront.",
    sailing: "The club's waters can be technical, with Atlantic pressure, chop and tide adding bite to dinghy and keelboat racing.",
    facilities: "Clubhouse, race support and marina proximity make it a natural base for local and visiting sailors working the Lisbon coast.",
    visitors: "Cascais is a useful stop for crews moving along the Portuguese coast, with marina services and a lively sailing community close at hand.",
  },
  "clubs-cowes-corinthian-yacht-club-ccyc": {
    title: "Cowes Corinthian Yacht Club (CCYC)",
    location: "Cowes, Isle of Wight",
    country: "United Kingdom",
    founded: "1952",
    website: { label: "Cowes Corinthian Yacht Club", url: "https://www.ccyc.org.uk/", host: "ccyc.org.uk" },
    mapQuery: "Cowes Corinthian Yacht Club, Cowes, Isle of Wight",
    setting: "a Cowes club with the Solent as its playground and enough tide outside the door to keep crews honest.",
    knownFor: "Corinthian racing, Cowes events and a strong local club identity on the Medina.",
    sailing: "Racing tends to be practical, tidal and close-quarters, with Solent marks, harbour traffic and summer regatta weeks all part of the business.",
    facilities: "The clubhouse gives crews a convenient Cowes base, with local marinas, yards and chandleries nearby.",
    visitors: "Visiting sailors should make berth plans early during Cowes Week and other Solent events, when the town fills fast.",
  },
  "clubs-golden-gate-yacht-club-ggyc": {
    title: "Golden Gate Yacht Club (GGYC)",
    location: "San Francisco, California",
    country: "United States",
    founded: "1939",
    website: { label: "Golden Gate Yacht Club", url: "https://www.ggyc.com/", host: "ggyc.com" },
    mapQuery: "Golden Gate Yacht Club, San Francisco, California",
    setting: "a San Francisco Bay club with big breeze, strong tide and the Golden Gate rarely far from view.",
    knownFor: "America's Cup history, bay racing and a no-nonsense sailing culture forged in proper breeze.",
    sailing: "The Bay rewards crews who can handle current, chop and sudden pressure changes; lazy trimming does not live long here.",
    facilities: "The club sits close to San Francisco marina services and offers a social and racing base for members and visiting sailors.",
    visitors: "Visitors should respect local tide tables, shipping traffic and the fact that San Francisco afternoon breeze can arrive with a grin and a slap.",
  },
  "clubs-hayling-island-sailing-club": {
    title: "Hayling Island Sailing Club",
    location: "Hayling Island, Hampshire",
    country: "United Kingdom",
    website: { label: "Hayling Island Sailing Club", url: "https://www.hisc.co.uk/", host: "hisc.co.uk" },
    mapQuery: "Hayling Island Sailing Club, Hayling Island, Hampshire",
    setting: "a major dinghy and small-boat club at the mouth of Chichester Harbour, with open water close by.",
    knownFor: "championship dinghy sailing, open meetings and a race area that can serve up flat water, tide and sea breeze in equal measure.",
    sailing: "The club is a serious dinghy venue, supporting youth sailing, class championships and race management across harbour and bay waters.",
    facilities: "Large dinghy parks, launching areas, clubhouse facilities and event infrastructure make it a strong base for visiting championships.",
    visitors: "Competitors should check event instructions, launch timing and tide heights before assuming the slipway will behave itself.",
  },
  "clubs-indian-harbor-yacht-club": {
    title: "Indian Harbor Yacht Club",
    location: "Greenwich, Connecticut",
    country: "United States",
    founded: "1889",
    website: { label: "Indian Harbor Yacht Club", url: "https://www.indianharboryc.com/", host: "indianharboryc.com" },
    mapQuery: "Indian Harbor Yacht Club, Greenwich, Connecticut",
    setting: "a Long Island Sound club with a deep East Coast racing pedigree and a handsome Greenwich waterfront base.",
    knownFor: "classic yacht-club tradition, Sound racing and a long record of serious offshore and one-design sailors.",
    sailing: "The racing mixes local Sound conditions with broader East Coast events, where tide, light patches and patient boat speed all matter.",
    facilities: "Clubhouse, harbour access and member services support racing crews, cruising owners and visiting yachts by arrangement.",
    visitors: "Visitors should arrange access in advance and treat Long Island Sound weather with the same respect as any larger water.",
  },
  "clubs-island-harbour-yacht-club-ihyc": {
    title: "Island Harbour Yacht Club (IHYC)",
    location: "Island Harbour, Isle of Wight",
    country: "United Kingdom",
    website: { label: "Island Harbour Yacht Club", url: "https://www.ihyc.org.uk/", host: "ihyc.org.uk" },
    mapQuery: "Island Harbour Yacht Club, Isle of Wight",
    setting: "a marina-based Isle of Wight club tucked away from the busier Cowes waterfront.",
    knownFor: "social cruising, local gatherings and a quieter island base for sailors who prefer a less frantic berth.",
    sailing: "The club suits cruising crews and Solent sailors using the Medina and Island Harbour as a practical starting point.",
    facilities: "Marina surroundings provide berthing, shore facilities and access to Isle of Wight cruising grounds.",
    visitors: "Check lock, tide and marina arrangements before arrival, as Island Harbour is more considered than simply pointing at the entrance and hoping.",
  },
  "clubs-itchenor-sailing-club-isc": {
    title: "Itchenor Sailing Club (ISC)",
    location: "Itchenor, Chichester Harbour",
    country: "United Kingdom",
    founded: "1927",
    website: { label: "Itchenor Sailing Club", url: "https://www.itchenorsc.co.uk/", host: "itchenorsc.co.uk" },
    mapQuery: "Itchenor Sailing Club, Chichester Harbour",
    setting: "a Chichester Harbour club with tidal creeks, classic dinghy fleets and a strong family sailing tradition.",
    knownFor: "dinghy racing, keelboat classes and harbour sailing that rewards local knowledge and a careful eye on the tide.",
    sailing: "Itchenor's sailing is technical rather than theatrical, with harbour channels, mud edges and shifting breeze keeping crews busy.",
    facilities: "The club offers launching, clubhouse facilities and race support for members, junior sailors and visiting events.",
    visitors: "Visiting boats should study harbour marks, mooring options and tide times before wandering up the channel.",
  },
  "clubs-new-york-yacht-club-nyyc": {
    title: "New York Yacht Club (NYYC)",
    location: "New York City and Newport, Rhode Island",
    country: "United States",
    founded: "1844",
    website: { label: "New York Yacht Club", url: "https://nyyc.org/", host: "nyyc.org" },
    telephone: "+1 (401) 846-1000",
    mapQuery: "New York Yacht Club Harbour Court Newport Rhode Island",
    setting: "one of the great names in world yachting, with its Manhattan clubhouse and Harbour Court sailing base in Newport.",
    knownFor: "America's Cup history, elite regattas, offshore racing and a formidable place in the sport's old ledger.",
    sailing: "The club's racing reaches from Newport one-design events to ocean work, with standards high enough to expose weak preparation quickly.",
    facilities: "Harbour Court gives the club a major waterside base, while the New York clubhouse preserves the institutional heart of the organisation.",
    visitors: "Access is formal and event-led; crews heading to Newport should plan around regatta instructions, harbour bookings and club protocol.",
  },
  "clubs-newport-harbor-yacht-club-nhyc": {
    title: "Newport Harbor Yacht Club (NHYC)",
    location: "Newport Beach, California",
    country: "United States",
    founded: "1916",
    website: { label: "Newport Harbor Yacht Club", url: "https://www.nhyc.org/", host: "nhyc.org" },
    mapQuery: "Newport Harbor Yacht Club, Newport Beach, California",
    setting: "a Southern California harbour club with sheltered water inside and Pacific racing outside.",
    knownFor: "junior sailing, match racing, harbour fleets and West Coast yacht-club tradition.",
    sailing: "Newport Harbor offers a useful mix: tight harbour work for small boats and open-water courses once crews clear the entrance.",
    facilities: "The club provides member hospitality, sailing programme support and access to the wider Newport Beach marine network.",
    visitors: "Visiting sailors should make arrangements early; Newport Beach is polished, popular and rarely short of boats.",
  },
  "clubs-newport-yacht-club-nyc-rhode-island": {
    title: "Newport Yacht Club (NYC - Rhode Island)",
    location: "Newport, Rhode Island",
    country: "United States",
    website: { label: "Newport Yacht Club", url: "https://www.newportyachtclub.org/", host: "newportyachtclub.org" },
    mapQuery: "Newport Yacht Club, Newport, Rhode Island",
    setting: "a working Newport harbour club in one of America's busiest and most historic sailing towns.",
    knownFor: "cruising, club racing and practical access to Narragansett Bay.",
    sailing: "The club sits in waters used by everything from dayboats to grand-prix fleets, with sea breeze, tide and traffic all part of the day.",
    facilities: "Clubhouse hospitality and harbour services make it a useful stop for crews using Newport as a base.",
    visitors: "During summer regatta periods, book early and expect the waterfront to be alive with launches, tenders and opinions.",
  },
  "clubs-real-club-nautico-de-barcelona-rcnb": {
    title: "Real Club Nautico de Barcelona (RCNB)",
    location: "Barcelona",
    country: "Spain",
    founded: "1876",
    website: { label: "Real Club Nautico de Barcelona", url: "https://www.rcnb.com/", host: "rcnb.com" },
    mapQuery: "Real Club Nautico de Barcelona, Barcelona, Spain",
    setting: "a historic Barcelona club based on one of the Mediterranean's busiest city waterfronts.",
    knownFor: "Mediterranean regattas, Spanish yacht-club tradition and a central position in Barcelona sailing.",
    sailing: "The club's waters offer coastal racing, offshore starts and a steady diet of Mediterranean wind shifts.",
    facilities: "Clubhouse, marina access and city marine services make it practical for visiting racing crews and cruising yachts.",
    visitors: "Barcelona is a busy port city, so visiting yachts should confirm marina arrangements and approach procedures before arrival.",
  },
  "clubs-royal-canadian-yacht-club-rcyc": {
    title: "Royal Canadian Yacht Club (RCYC)",
    location: "Toronto, Ontario",
    country: "Canada",
    founded: "1852",
    website: { label: "Royal Canadian Yacht Club", url: "https://rcyc.ca/", host: "rcyc.ca" },
    mapQuery: "Royal Canadian Yacht Club, Toronto, Ontario",
    setting: "a Lake Ontario institution with island and city connections in Toronto.",
    knownFor: "Canadian yacht-club history, dinghy and keelboat racing, and a strong junior sailing culture.",
    sailing: "Lake Ontario can look polite from shore and then deliver real breeze, chop and long-course work once crews are out in it.",
    facilities: "The club supports racing, cruising, junior sailing, dining and member services from a well-established waterfront base.",
    visitors: "Visiting sailors should check club access and launch/harbour arrangements, especially around major summer events.",
  },
  "clubs-royal-cape-yacht-club-rcyc": {
    title: "Royal Cape Yacht Club (RCYC)",
    location: "Cape Town",
    country: "South Africa",
    founded: "1905",
    website: { label: "Royal Cape Yacht Club", url: "https://rcyc.co.za/", host: "rcyc.co.za" },
    mapQuery: "Royal Cape Yacht Club, Cape Town, South Africa",
    setting: "a Cape Town club with Table Bay, working harbour water and serious ocean routes close at hand.",
    knownFor: "South African offshore racing, cruising support and a strong Cape sailing community.",
    sailing: "The Cape does not flatter the unprepared; wind, swell and ocean miles make this a club with proper seagoing relevance.",
    facilities: "Clubhouse, marina surroundings and local marine services support both coastal sailors and ocean-bound crews.",
    visitors: "Visiting yachts should check harbour procedures, weather windows and local advice before treating Table Bay as just another stop.",
  },
  "clubs-royal-cork-yacht-club-rcyc": {
    title: "Royal Cork Yacht Club (RCYC)",
    location: "Crosshaven, County Cork",
    country: "Ireland",
    founded: "1720",
    website: { label: "Royal Cork Yacht Club", url: "https://www.royalcork.com/", host: "royalcork.com" },
    mapQuery: "Royal Cork Yacht Club, Crosshaven, County Cork",
    setting: "a Crosshaven club on Cork Harbour, carrying one of the oldest names in organised yachting.",
    knownFor: "deep yachting history, Cork Week, harbour racing and a proper Irish welcome after a wet beat.",
    sailing: "Cork Harbour offers protected racing and quick access to open water, with tide, breeze and rolling weather all in play.",
    facilities: "The club has the scale for major events, junior sailing, cruiser racing and visiting crews using the harbour.",
    visitors: "Crosshaven is a natural sailing stop; visitors should check event dates and berth availability when the big fleets are in town.",
  },
  "clubs-royal-hong-kong-yacht-club-rhkyc": {
    title: "Royal Hong Kong Yacht Club (RHKYC)",
    location: "Hong Kong",
    country: "Hong Kong",
    founded: "1890",
    website: { label: "Royal Hong Kong Yacht Club", url: "https://www.rhkyc.org.hk/", host: "rhkyc.org.hk" },
    mapQuery: "Royal Hong Kong Yacht Club, Hong Kong",
    setting: "a major Asian yacht club with bases serving Victoria Harbour and Hong Kong's broader sailing waters.",
    knownFor: "harbour racing, offshore events, dinghy sailing and a busy social calendar in one of the world's great port cities.",
    sailing: "The racing ranges from close harbour work to offshore passages, with traffic, tide and tropical weather always worth respecting.",
    facilities: "Multiple club bases, racing support, training activity and member hospitality give RHKYC serious reach.",
    visitors: "Visiting sailors should check access and event arrangements, especially when typhoon-season planning and harbour traffic are factors.",
  },
  "clubs-royal-lymington-yacht-club-rlymyc": {
    title: "Royal Lymington Yacht Club (RLymYC)",
    location: "Lymington, Hampshire",
    country: "United Kingdom",
    founded: "1922",
    website: { label: "Royal Lymington Yacht Club", url: "https://rlymyc.org.uk/", host: "rlymyc.org.uk" },
    mapQuery: "Royal Lymington Yacht Club, Lymington, Hampshire",
    setting: "a western Solent club with the Lymington River, Hurst Narrows and the Isle of Wight close by.",
    knownFor: "youth sailing, keelboat racing, cruising and a smart position on one of Britain's best sailing stretches.",
    sailing: "The western Solent brings tide, shallow edges and brisk breeze, which is excellent news for sailors who enjoy being found out.",
    facilities: "Clubhouse facilities, river access and local marina services make Lymington a practical base for cruising and racing.",
    visitors: "Visiting crews should plan river access and berthing early during summer weekends and Solent event weeks.",
  },
  "clubs-royal-new-zealand-yacht-squadron-rnzys": {
    title: "Royal New Zealand Yacht Squadron (RNZYS)",
    location: "Auckland",
    country: "New Zealand",
    founded: "1871",
    website: { label: "Royal New Zealand Yacht Squadron", url: "https://www.rnzys.org.nz/", host: "rnzys.org.nz" },
    mapQuery: "Royal New Zealand Yacht Squadron, Auckland, New Zealand",
    setting: "an Auckland club on the Waitemata Harbour, in a city that treats sailing as part sport, part civic habit.",
    knownFor: "America's Cup pedigree, harbour racing, youth development and a national sailing profile far larger than its postcode.",
    sailing: "Auckland's harbour racing is tactical and busy, with breeze lanes, ferry wash and sharp crews all fighting for space.",
    facilities: "The Squadron offers club hospitality, race management and training links in one of the world's most active sailing cities.",
    visitors: "Visiting sailors should check regatta dates, berth options and local harbour rules before joining the Auckland shuffle.",
  },
  "clubs-royal-ocean-racing-club-rorc": {
    title: "Royal Ocean Racing Club (RORC)",
    location: "London and Cowes",
    country: "United Kingdom",
    founded: "1925",
    website: { label: "Royal Ocean Racing Club", url: "https://www.rorc.org/", host: "rorc.org" },
    mapQuery: "Royal Ocean Racing Club, Cowes, Isle of Wight",
    setting: "an offshore racing club with London roots, a Cowes presence and a calendar that has sent many crews home shorter on sleep.",
    knownFor: "the Fastnet Race, offshore championships, IRC racing and serious race management.",
    sailing: "RORC racing is offshore by nature: tides, night work, weather routing, watch systems and the honest business of keeping a boat moving.",
    facilities: "The club supports race organisation, member hospitality and offshore administration rather than acting as a simple marina club.",
    visitors: "Crews should read race documents properly; RORC events reward preparation and have little sympathy for optimistic paperwork.",
  },
  "clubs-royal-southern-yacht-club-rsrnyc": {
    title: "Royal Southern Yacht Club (RSrnYC)",
    location: "Hamble, Hampshire",
    country: "United Kingdom",
    founded: "1837",
    website: { label: "Royal Southern Yacht Club", url: "https://www.royal-southern.co.uk/", host: "royal-southern.co.uk" },
    mapQuery: "Royal Southern Yacht Club, Hamble, Hampshire",
    setting: "a Hamble River club with the Solent only a short motor away and racing fleets never far from the bar talk.",
    knownFor: "Solent racing, keelboat events, youth sailing and a long-established royal yacht-club tradition.",
    sailing: "The club's programme leans into Solent marks, Hamble starts, class racing and the kind of tide that punishes casual navigation.",
    facilities: "Clubhouse, pontoons, event support and nearby Hamble marine services make it a strong base for racing crews.",
    visitors: "The Hamble is busy, narrow and full of people who think they know the right of way; approach with patience and fenders ready.",
  },
  "clubs-royal-swedish-yacht-club-ksss": {
    title: "Royal Swedish Yacht Club (KSSS)",
    location: "Stockholm and Sandhamn",
    country: "Sweden",
    founded: "1830",
    website: { label: "Royal Swedish Yacht Club", url: "https://www.ksss.se/", host: "ksss.se" },
    mapQuery: "KSSS Sandhamn, Sweden",
    setting: "a Swedish club tied to Stockholm and the archipelago, with Sandhamn as one of its great sailing stages.",
    knownFor: "Baltic racing, archipelago sailing, Olympic development and a long royal-club history.",
    sailing: "The waters demand careful navigation, with islands, rocks, channels and clean northern breeze giving crews plenty to think about.",
    facilities: "Club bases, racing organisation and training activity support sailors from juniors to offshore crews.",
    visitors: "Cruising sailors should respect archipelago navigation and confirm harbour arrangements before assuming every pretty inlet has space.",
  },
  "clubs-royal-sydney-yacht-squadron-rsys": {
    title: "Royal Sydney Yacht Squadron (RSYS)",
    location: "Kirribilli, Sydney",
    country: "Australia",
    founded: "1862",
    website: { label: "Royal Sydney Yacht Squadron", url: "https://www.rsys.com.au/", host: "rsys.com.au" },
    mapQuery: "Royal Sydney Yacht Squadron, Kirribilli, Sydney",
    setting: "a Sydney Harbour club at Kirribilli, with one of the finest city sailing backdrops anywhere.",
    knownFor: "harbour racing, keelboats, dinghies and Australian yacht-club history.",
    sailing: "Sydney Harbour sailing mixes postcard views with ferries, gusts, short legs and tactical corners that can ruin a confident start.",
    facilities: "The club has waterfront facilities, race organisation, training and access to a deep local sailing community.",
    visitors: "Visitors should check harbour traffic, event notices and club access before treating Sydney Harbour as a scenic free-for-all.",
  },
  "clubs-royal-thames-yacht-club-rtyc": {
    title: "Royal Thames Yacht Club (RTYC)",
    location: "Knightsbridge, London and Cowes",
    country: "United Kingdom",
    founded: "1775",
    website: { label: "Royal Thames Yacht Club", url: "https://www.royalthames.com/", host: "royalthames.com" },
    mapQuery: "Royal Thames Yacht Club, Knightsbridge, London",
    setting: "a London club with deep racing history and enduring connections to Cowes and the wider Solent scene.",
    knownFor: "being among the oldest yacht clubs in the world, match racing, team racing and a distinguished social and racing calendar.",
    sailing: "The club's programme reaches beyond its London address through Solent events, team racing and regattas run with old-school precision.",
    facilities: "The clubhouse provides the formal centre of club life, while racing activity is often delivered through established sailing venues.",
    visitors: "Access is club-led and event-specific; visiting sailors should arrange invitations, entries and berthing through the proper channels.",
  },
  "clubs-royal-yacht-squadron-rys": {
    title: "Royal Yacht Squadron (RYS)",
    location: "Cowes, Isle of Wight",
    country: "United Kingdom",
    founded: "1815",
    website: { label: "Royal Yacht Squadron", url: "https://www.rys.org.uk/", host: "rys.org.uk" },
    mapQuery: "Royal Yacht Squadron, Cowes, Isle of Wight",
    setting: "the Castle at Cowes, looking out across the Solent from one of yachting's most recognisable addresses.",
    knownFor: "America's Cup origins, Cowes Week, royal patronage and the start lines that have launched a century of ambition.",
    sailing: "The Squadron's sailing history is tied to big-boat racing, Solent starts and the formal machinery of premier regattas.",
    facilities: "The Castle remains a private club base rather than a marina, with Cowes services and harbour berths nearby for visiting yachts.",
    visitors: "Most sailors see it from the water; visits are formal, but the line off Cowes is a public education in yachting history.",
  },
  "clubs-san-diego-yacht-club-sdyc": {
    title: "San Diego Yacht Club (SDYC)",
    location: "San Diego, California",
    country: "United States",
    founded: "1886",
    website: { label: "San Diego Yacht Club", url: "https://sdyc.org/", host: "sdyc.org" },
    mapQuery: "San Diego Yacht Club, San Diego, California",
    setting: "a major West Coast club on San Diego Bay, with warm-water sailing and a serious racing culture.",
    knownFor: "America's Cup history, junior sailing, offshore racing and a strong calendar of Southern California events.",
    sailing: "The club's sailors work inside the bay and offshore, where light air, sea breeze and Pacific swell each get a vote.",
    facilities: "Clubhouse, marina surroundings, race support and training programmes make it a complete yacht-club base.",
    visitors: "Visiting crews should check guest arrangements and local harbour rules, particularly around events and busy weekends.",
  },
  "clubs-sanya-serenity-marina": {
    title: "Sanya Serenity Marina",
    location: "Sanya, Hainan",
    country: "China",
    website: { label: "Sanya Serenity Marina", url: "https://www.sanyaserenitymarina.com/", host: "sanyaserenitymarina.com" },
    mapQuery: "Sanya Serenity Marina, Sanya, Hainan, China",
    setting: "a Chinese marina and sailing venue on Hainan, built around warm-water cruising and international race stopovers.",
    knownFor: "hosting major offshore race activity, superyacht berthing and China's developing leisure marine scene.",
    sailing: "The waters around Sanya offer tropical conditions, monsoon-season considerations and access to South China Sea passages.",
    facilities: "Marina berths, event infrastructure, shore services and yacht support form the practical core of the site.",
    visitors: "International crews should check arrival, customs and marina procedures carefully before treating it like a simple domestic stop.",
  },
  "clubs-societe-nautique-de-saint-tropez-snst": {
    title: "Societe Nautique de Saint-Tropez (SNST)",
    location: "Saint-Tropez",
    country: "France",
    founded: "1862",
    website: { label: "Societe Nautique de Saint-Tropez", url: "https://www.snst.org/", host: "snst.org" },
    mapQuery: "Societe Nautique de Saint-Tropez, Saint-Tropez, France",
    setting: "a Riviera club in Saint-Tropez, where classic yachts, modern racers and harbour theatre all share the same water.",
    knownFor: "Les Voiles de Saint-Tropez, Mediterranean regattas and a link between old varnish and modern carbon.",
    sailing: "The local programme benefits from Gulf of Saint-Tropez conditions, coastal courses and fleets that often look as good as they sail.",
    facilities: "Club facilities and port services support regattas, visiting crews and the busy social side of Saint-Tropez sailing.",
    visitors: "Visiting yachts should plan well ahead; Saint-Tropez is glamorous, crowded and not known for spare space in peak season.",
  },
  "clubs-st-francis-yacht-club-stfyc": {
    title: "St. Francis Yacht Club (StFYC)",
    location: "San Francisco, California",
    country: "United States",
    founded: "1927",
    website: { label: "St. Francis Yacht Club", url: "https://www.stfyc.com/", host: "stfyc.com" },
    mapQuery: "St. Francis Yacht Club, San Francisco, California",
    setting: "a San Francisco Bay club at the sharp end of breeze, tide and high-standard race management.",
    knownFor: "the Rolex Big Boat Series, championship fleets and a front-row position on one of the world's great racing waters.",
    sailing: "The Bay asks for fast hands and calm heads, with current, chop and pressure giving every start line a bit of theatre.",
    facilities: "Waterfront clubhouse facilities, regatta organisation and member services support major events and local racing.",
    visitors: "Bring layers, read the tide book and do not assume the Golden Gate breeze is interested in your comfort.",
  },
  "clubs-warsash-sailing-club-wsc": {
    title: "Warsash Sailing Club (WSC)",
    location: "Warsash, Hampshire",
    country: "United Kingdom",
    website: { label: "Warsash Sailing Club", url: "https://www.warsashsc.org.uk/", host: "warsashsc.org.uk" },
    mapQuery: "Warsash Sailing Club, Hampshire",
    setting: "a River Hamble club close to Southampton Water and the Solent race areas.",
    knownFor: "club racing, dinghy activity and its place in the practical Hamble sailing community.",
    sailing: "Warsash sailors work with river traffic, Solent tide and a busy local racing scene where starts can be crowded and lively.",
    facilities: "Clubhouse facilities, launching and nearby Hamble marine services support local sailors and visiting competitors.",
    visitors: "Approach with care around river traffic and check event instructions before assuming the Hamble will be quiet.",
  },
  "clubs-yacht-club-como": {
    title: "Yacht Club Como",
    location: "Como, Lake Como",
    country: "Italy",
    website: { label: "Yacht Club Como", url: "https://www.yachtclubcomo.it/", host: "yachtclubcomo.it" },
    mapQuery: "Yacht Club Como, Lake Como, Italy",
    setting: "an Italian lake club with steep shores, shifting breeze and one of Europe's most elegant sailing backdrops.",
    knownFor: "lake sailing, local regattas and a setting that makes even a poor tack look scenic.",
    sailing: "Lake Como rewards sailors who read the wind on the hillsides, where pressure can arrive in stripes rather than polite announcements.",
    facilities: "The club provides a base for local racing, training and social sailing on the lake.",
    visitors: "Visiting sailors should check local access, storage and event arrangements, as lake venues often work differently from coastal marinas.",
  },
  "clubs-yacht-club-de-monaco": {
    title: "Yacht Club de Monaco",
    location: "Monaco",
    country: "Monaco",
    founded: "1953",
    website: { label: "Yacht Club de Monaco", url: "https://www.yacht-club-monaco.mc/", host: "yacht-club-monaco.mc" },
    mapQuery: "Yacht Club de Monaco, Monaco",
    setting: "a high-profile Mediterranean club overlooking Port Hercules, with superyachts and racing yachts sharing the same glamorous stage.",
    knownFor: "classic yacht events, superyacht culture, Monaco regattas and a clubhouse that signals serious intent before the docklines are even tied.",
    sailing: "Monaco's sailing ranges from classic gatherings to modern race events, with Mediterranean weather and tight harbour logistics part of the game.",
    facilities: "The club offers major-event hospitality, yacht-club services and direct access to one of the best-known ports in the world.",
    visitors: "Berthing and access should be arranged early, especially around grand prix weeks, yacht shows and headline regattas.",
  },
  "clubs-yacht-club-of-greece-nautical-club-of-greece": {
    title: "Yacht Club of Greece (Nautical Club of Greece)",
    location: "Piraeus, Athens",
    country: "Greece",
    website: { label: "Yacht Club of Greece", url: "https://www.ycg.gr/", host: "ycg.gr" },
    mapQuery: "Yacht Club of Greece, Piraeus, Athens",
    setting: "a Greek yacht club near Athens, with the Saronic Gulf and Aegean cruising grounds close by.",
    knownFor: "Greek yachting tradition, racing, cruising links and a commanding position above classic Mediterranean waters.",
    sailing: "The sailing can move from sheltered gulf work to Aegean passages, where summer meltemi and hard sunlight make lazy preparation expensive.",
    facilities: "Clubhouse, race activity and links to the Athens marine scene make it a natural focal point for Greek sailors.",
    visitors: "Crews should check local arrangements, weather patterns and marina options before pushing out into the islands.",
  },
};

export function getClubProfile(slug: string) {
  return clubProfiles[slug] ?? null;
}

export function getClubProfileForStory(story: Pick<EditableStory, "category" | "slug">) {
  return categoryMatchesLabel(story.category, "Clubs") ? getClubProfile(story.slug) : null;
}

export function getClubProfileExcerpt(story: Pick<EditableStory, "category" | "slug" | "summary">) {
  const profile = getClubProfileForStory(story);
  if (!profile) return story.summary;
  return `${profile.title} is based in ${profile.location}, ${profile.country}. It is known for ${profile.knownFor}`;
}

export function getClubProfileArticleBody(profile: ClubProfile) {
  return [
    `${profile.title} is based in ${profile.location}, ${profile.country}. It is ${profile.setting}`,
    `${profile.founded ? `Founded in ${profile.founded}, it has ` : "It has "}become known for ${profile.knownFor}`,
    `On the water, ${profile.sailing}`,
    `Ashore, ${profile.facilities}`,
    `For visiting sailors, ${profile.visitors}`,
  ];
}
