export type SourceWatchSite = {
  id: string;
  name: string;
  url: string;
  group: string;
  focus: string;
  sections: string[];
  storyStyle: string;
  photoRule: string;
  approvalRule: string;
  feedUrls: string[];
  checkEveryHours: number;
  status: "active" | "inactive";
};

const defaultStoryStyle =
  "Rewrite into a standalone Old Sea Dogs editorial draft with no source-attribution wording, no copied phrasing, and no automatic publishing.";
const defaultPhotoRule =
  "Do not use third-party photos unless Old Sea Dogs has direct permission and a visible credit.";
const defaultApprovalRule = "Create a private review draft. Editor approval is required before anything appears publicly.";

function source(input: Omit<SourceWatchSite, "storyStyle" | "photoRule" | "approvalRule" | "checkEveryHours" | "status"> & {
  checkEveryHours?: number;
  status?: "active" | "inactive";
}): SourceWatchSite {
  return {
    ...input,
    storyStyle: defaultStoryStyle,
    photoRule: defaultPhotoRule,
    approvalRule: defaultApprovalRule,
    checkEveryHours: input.checkEveryHours ?? 6,
    status: input.status ?? "active",
  };
}

export const sourceWatchSites: SourceWatchSite[] = [
  source({
    id: "sail-world",
    name: "Sail-World",
    url: "https://www.sail-world.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.sail-world.com/rss"],
    focus: "Sailing news, dinghy and yacht racing, regattas, clubs, events, and race reports.",
    sections: ["News", "Races", "Clubs", "Gear", "Masterclass"],
  }),
  source({
    id: "yachting-world",
    name: "Yachting World",
    url: "https://www.yachtingworld.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.yachtingworld.com/feed", "https://www.yachtingworld.com/news"],
    focus: "Bluewater sailing, yacht tests, ocean passages, events, racing and cruising seamanship.",
    sections: ["News", "Races", "Reviews", "Destinations", "Masterclass"],
  }),
  source({
    id: "sailing-world",
    name: "Sailing World",
    url: "https://www.sailingworld.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.sailingworld.com/feed/", "https://www.sailingworld.com/racing/"],
    focus: "Racing, one-design fleets, sailing gear, technique and North American sailing news.",
    sections: ["News", "Races", "Gear", "Masterclass"],
  }),
  source({
    id: "scuttlebutt",
    name: "Scuttlebutt Sailing News",
    url: "https://www.sailingscuttlebutt.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.sailingscuttlebutt.com/feed/"],
    focus: "Daily sailing news, race results, offshore notes, clubs and short-form sailing updates.",
    sections: ["News", "Races", "Clubs"],
  }),
  source({
    id: "sailweb",
    name: "SailWeb",
    url: "https://www.sailweb.co.uk",
    group: "Daily sailing news",
    feedUrls: ["https://www.sailweb.co.uk/feed/", "https://www.sailweb.co.uk/"],
    focus: "UK sailing, Olympic classes, dinghy results, yacht racing and event reports.",
    sections: ["News", "Races", "Clubs"],
  }),
  source({
    id: "ybw",
    name: "YBW",
    url: "https://www.ybw.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.ybw.com/feed", "https://www.ybw.com/news"],
    focus: "Boating news, practical cruising, boats, ownership and UK marine stories.",
    sections: ["News", "Reviews", "Gear", "Destinations", "Masterclass"],
  }),
  source({
    id: "yachting-monthly",
    name: "Yachting Monthly",
    url: "https://www.yachtingmonthly.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.yachtingmonthly.com/feed", "https://www.yachtingmonthly.com/news"],
    focus: "Cruising, seamanship, gear, boat ownership, passages and practical sailing.",
    sections: ["News", "Destinations", "Gear", "Masterclass"],
  }),
  source({
    id: "cruising-world",
    name: "Cruising World",
    url: "https://www.cruisingworld.com",
    group: "Daily sailing news",
    feedUrls: ["https://www.cruisingworld.com/feed/", "https://www.cruisingworld.com/sailboats/"],
    focus: "Cruising yachts, liveaboard stories, charter, gear, boat tests and ocean sailing.",
    sections: ["News", "Reviews", "Destinations", "Gear", "Lifestyle"],
  }),
  source({
    id: "rorc",
    name: "Royal Ocean Racing Club",
    url: "https://www.rorc.org",
    group: "Racing and offshore",
    feedUrls: ["https://www.rorc.org/news", "https://www.rorc.org/"],
    focus: "Offshore racing, RORC events, trophies, fleets, results and race notices.",
    sections: ["Races", "Clubs", "News"],
  }),
  source({
    id: "cowes-week",
    name: "Cowes Week",
    url: "https://www.cowesweek.co.uk",
    group: "Racing and offshore",
    feedUrls: ["https://www.cowesweek.co.uk/web/code/php/main_c.php?section=news", "https://www.cowesweek.co.uk/"],
    focus: "Cowes Week news, Solent race updates, entries, results and shore-side stories.",
    sections: ["Races", "Shows", "Clubs"],
  }),
  source({
    id: "rolex-fastnet-race",
    name: "Rolex Fastnet Race",
    url: "https://www.rolexfastnetrace.com",
    group: "Racing and offshore",
    feedUrls: ["https://www.rolexfastnetrace.com/en/news", "https://www.rolexfastnetrace.com"],
    focus: "Fastnet entries, race updates, offshore fleets, results and course stories.",
    sections: ["Races", "News"],
  }),
  source({
    id: "sydney-hobart",
    name: "Sydney Hobart Yacht Race",
    url: "https://rolexsydneyhobart.com",
    group: "Racing and offshore",
    feedUrls: ["https://rolexsydneyhobart.com/news/", "https://rolexsydneyhobart.com/"],
    focus: "Sydney Hobart race news, fleets, weather, line honours, crews and results.",
    sections: ["Races", "News"],
  }),
  source({
    id: "newport-bermuda-race",
    name: "Newport Bermuda Race",
    url: "https://bermudarace.com",
    group: "Racing and offshore",
    feedUrls: ["https://bermudarace.com/feed/", "https://bermudarace.com/news/"],
    focus: "Newport Bermuda Race entries, offshore updates, notices, crew stories and results.",
    sections: ["Races", "News"],
  }),
  source({
    id: "caribbean-600",
    name: "Caribbean 600",
    url: "https://caribbean600.rorc.org",
    group: "Racing and offshore",
    feedUrls: ["https://caribbean600.rorc.org/news", "https://caribbean600.rorc.org"],
    focus: "RORC Caribbean 600 fleet news, conditions, classes, teams and results.",
    sections: ["Races", "Destinations", "News"],
  }),
  source({
    id: "transpac",
    name: "Transpacific Yacht Race",
    url: "https://transpacyc.com",
    group: "Racing and offshore",
    feedUrls: ["https://transpacyc.com/news", "https://transpacyc.com/"],
    focus: "Transpac race news, ocean racing teams, course updates, boats and results.",
    sections: ["Races", "News"],
  }),
  source({
    id: "the-ocean-race",
    name: "The Ocean Race",
    url: "https://www.theoceanrace.com",
    group: "Racing and offshore",
    feedUrls: ["https://www.theoceanrace.com/en/news", "https://www.theoceanrace.com"],
    focus: "Ocean Race crews, legs, IMOCA news, offshore conditions and race results.",
    sections: ["Races", "News", "Lifestyle"],
  }),
  source({
    id: "sailgp",
    name: "SailGP",
    url: "https://sailgp.com",
    group: "Racing and offshore",
    feedUrls: ["https://sailgp.com/news/", "https://sailgp.com/"],
    focus: "SailGP events, teams, foiling fleets, results, venues and technology.",
    sections: ["Races", "News", "Gear"],
  }),
  source({
    id: "tp52-super-series",
    name: "TP52 Super Series",
    url: "https://www.52superseries.com",
    group: "Racing and offshore",
    feedUrls: ["https://www.52superseries.com/feed/", "https://www.52superseries.com/news/"],
    focus: "TP52 fleet racing, teams, regattas, race reports and results.",
    sections: ["Races", "News"],
  }),
  source({
    id: "j-class",
    name: "J Class Association",
    url: "https://jclassyachts.com",
    group: "Racing and offshore",
    feedUrls: ["https://jclassyachts.com/feed/", "https://jclassyachts.com/news/"],
    focus: "J Class yachts, classics, events, restorations and racing.",
    sections: ["Races", "Lifestyle", "Reviews"],
  }),
  source({
    id: "ilca",
    name: "ILCA",
    url: "https://ilca.org",
    group: "Racing and offshore",
    feedUrls: ["https://ilca.org/feed/", "https://ilca.org/news/"],
    focus: "ILCA class news, championships, sailors, fleets and race results.",
    sections: ["Races", "News", "Clubs"],
  }),
  source({
    id: "world-sailing",
    name: "World Sailing",
    url: "https://www.sailing.org",
    group: "Racing and offshore",
    feedUrls: ["https://www.sailing.org/news/", "https://www.sailing.org"],
    focus: "International sailing federation news, events, classes, rules and championships.",
    sections: ["Races", "News", "Clubs"],
  }),
  source({
    id: "royal-yacht-squadron",
    name: "Royal Yacht Squadron",
    url: "https://www.rys.org.uk",
    group: "Clubs and institutions",
    feedUrls: ["https://www.rys.org.uk/news", "https://www.rys.org.uk"],
    focus: "Club news, racing, events, traditions and Solent activity.",
    sections: ["Clubs", "Races", "Lifestyle"],
  }),
  source({
    id: "royal-thames-yacht-club",
    name: "Royal Thames Yacht Club",
    url: "https://www.royalthames.com",
    group: "Clubs and institutions",
    feedUrls: ["https://www.royalthames.com/news", "https://www.royalthames.com"],
    focus: "Club news, racing, London sailing, events and member activity.",
    sections: ["Clubs", "Races", "Lifestyle"],
  }),
  source({
    id: "new-york-yacht-club",
    name: "New York Yacht Club",
    url: "https://nyyc.org",
    group: "Clubs and institutions",
    feedUrls: ["https://nyyc.org/news", "https://nyyc.org/"],
    focus: "Club racing, regattas, America's Cup history, Newport events and institutional news.",
    sections: ["Clubs", "Races", "News"],
  }),
  source({
    id: "yacht-club-de-monaco",
    name: "Yacht Club de Monaco",
    url: "https://www.yacht-club-monaco.mc",
    group: "Clubs and institutions",
    feedUrls: ["https://www.yacht-club-monaco.mc/en/news/", "https://www.yacht-club-monaco.mc"],
    focus: "Monaco club news, classics, regattas, sustainability and superyacht events.",
    sections: ["Clubs", "Races", "Shows", "Lifestyle"],
  }),
  source({
    id: "royal-hong-kong-yacht-club",
    name: "Royal Hong Kong Yacht Club",
    url: "https://www.rhkyc.org.hk",
    group: "Clubs and institutions",
    feedUrls: ["https://www.rhkyc.org.hk/news", "https://www.rhkyc.org.hk/"],
    focus: "Hong Kong club racing, sailing programmes, regattas and club news.",
    sections: ["Clubs", "Races", "News"],
  }),
  source({
    id: "royal-new-zealand-yacht-squadron",
    name: "Royal New Zealand Yacht Squadron",
    url: "https://rnzys.org.nz",
    group: "Clubs and institutions",
    feedUrls: ["https://rnzys.org.nz/feed/", "https://rnzys.org.nz/news/"],
    focus: "New Zealand club racing, America's Cup connections, training and member news.",
    sections: ["Clubs", "Races", "News"],
  }),
  source({
    id: "royal-cork-yacht-club",
    name: "Royal Cork Yacht Club",
    url: "https://www.royalcork.com",
    group: "Clubs and institutions",
    feedUrls: ["https://www.royalcork.com/feed/", "https://www.royalcork.com/news/"],
    focus: "Cork sailing, club racing, youth sailing, harbour events and member news.",
    sections: ["Clubs", "Races", "News"],
  }),
  source({
    id: "island-sailing-club",
    name: "Island Sailing Club",
    url: "https://www.islandsc.org.uk",
    group: "Clubs and institutions",
    feedUrls: ["https://www.islandsc.org.uk/news", "https://www.islandsc.org.uk"],
    focus: "Round the Island Race, Solent sailing, club news and events.",
    sections: ["Clubs", "Races", "News"],
  }),
  source({
    id: "cruising-association",
    name: "Cruising Association",
    url: "https://www.theca.org.uk",
    group: "Clubs and institutions",
    feedUrls: ["https://www.theca.org.uk/news", "https://www.theca.org.uk"],
    focus: "Cruising knowledge, member news, destinations, navigation and practical advice.",
    sections: ["Clubs", "Destinations", "Masterclass"],
  }),
  source({
    id: "southampton-boat-show",
    name: "Southampton International Boat Show",
    url: "https://www.southamptonboatshow.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.southamptonboatshow.com/news", "https://www.southamptonboatshow.com"],
    focus: "Southampton show news, exhibitors, launches, gear and industry events.",
    sections: ["Shows", "News", "Gear", "Reviews"],
  }),
  source({
    id: "cannes-yachting-festival",
    name: "Cannes Yachting Festival",
    url: "https://www.cannesyachtingfestival.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.cannesyachtingfestival.com/en-gb/news.html", "https://www.cannesyachtingfestival.com"],
    focus: "Cannes show news, launches, exhibitors, boats and European industry stories.",
    sections: ["Shows", "News", "Reviews", "Lifestyle"],
  }),
  source({
    id: "boot-dusseldorf",
    name: "boot Dusseldorf",
    url: "https://www.boot.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.boot.com/en/Media_News/Press", "https://www.boot.com"],
    focus: "Dusseldorf boat show news, exhibitors, launches, gear and international marine business.",
    sections: ["Shows", "News", "Gear", "Reviews"],
  }),
  source({
    id: "monaco-yacht-show",
    name: "Monaco Yacht Show",
    url: "https://www.monacoyachtshow.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.monacoyachtshow.com/en/news", "https://www.monacoyachtshow.com"],
    focus: "Monaco Yacht Show exhibitors, superyacht launches, events, brokers and luxury marine news.",
    sections: ["Shows", "News", "Lifestyle"],
  }),
  source({
    id: "metstrade",
    name: "METSTRADE",
    url: "https://www.metstrade.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.metstrade.com/news", "https://www.metstrade.com"],
    focus: "Marine equipment, trade, technical systems, show news and supplier stories.",
    sections: ["Shows", "Gear", "News", "Masterclass"],
  }),
  source({
    id: "british-marine",
    name: "British Marine",
    url: "https://www.britishmarine.co.uk",
    group: "Boat shows and industry",
    feedUrls: ["https://www.britishmarine.co.uk/news", "https://www.britishmarine.co.uk"],
    focus: "UK marine industry news, trade, boat shows, policy, yards and business updates.",
    sections: ["News", "Shows", "Gear"],
  }),
  source({
    id: "boat-international",
    name: "Boat International",
    url: "https://www.boatinternational.com",
    group: "Boat shows and industry",
    feedUrls: [
      "https://www.boatinternational.com/yachts/news",
      "https://www.boatinternational.com/yacht-market-intelligence/brokerage-sales-news",
      "https://www.boatinternational.com/features-reviews",
    ],
    focus: "Superyacht launches, sales, charter, design, destinations, and major show stories.",
    sections: ["News", "Shows", "Reviews", "Destinations", "Lifestyle"],
  }),
  source({
    id: "superyacht-times",
    name: "SuperYacht Times",
    url: "https://www.superyachttimes.com",
    group: "Boat shows and industry",
    feedUrls: ["https://www.superyachttimes.com/yacht-news", "https://www.superyachttimes.com"],
    focus: "Superyacht fleet, sales, launches, refits, builders, brokerage and market news.",
    sections: ["News", "Reviews", "Lifestyle", "Shows"],
  }),
  source({
    id: "superyacht-news",
    name: "SuperyachtNews",
    url: "https://www.superyachtnews.com",
    group: "Boat shows and industry",
    feedUrls: [
      "https://www.superyachtnews.com/sitemapnews.xml",
      "https://www.superyachtnews.com/business",
      "https://www.superyachtnews.com/owner",
      "https://www.superyachtnews.com/crew",
      "https://www.superyachtnews.com/operations",
    ],
    focus: "Superyacht industry news, builders, refit, design, business, crew, regulation, and market stories.",
    sections: ["News", "Lifestyle", "Gear", "Shows", "Ports"],
  }),
  source({
    id: "noonsite",
    name: "Noonsite",
    url: "https://www.noonsite.com",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.noonsite.com/feed/", "https://www.noonsite.com/news/"],
    focus: "Cruising news, country notes, ports, clearance, routes and practical voyaging information.",
    sections: ["Destinations", "Ports", "Masterclass", "News"],
  }),
  source({
    id: "practical-boat-owner",
    name: "Practical Boat Owner",
    url: "https://www.pbo.co.uk",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.pbo.co.uk/feed", "https://www.pbo.co.uk/news"],
    focus: "Practical boating, maintenance, gear, cruising, boat ownership and hands-on advice.",
    sections: ["Masterclass", "Gear", "News", "Destinations"],
  }),
  source({
    id: "all-at-sea",
    name: "All At Sea",
    url: "https://www.allatsea.co.uk",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.allatsea.co.uk/feed/", "https://www.allatsea.co.uk/news/"],
    focus: "UK boating news, clubs, cruising, shows, people and waterfront life.",
    sections: ["News", "Clubs", "Shows", "Lifestyle"],
  }),
  source({
    id: "classic-boat",
    name: "Classic Boat",
    url: "https://www.classicboat.co.uk",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.classicboat.co.uk/feed", "https://www.classicboat.co.uk/news"],
    focus: "Classic yachts, restorations, regattas, wooden boats, people and heritage.",
    sections: ["Lifestyle", "Races", "Reviews", "Clubs"],
  }),
  source({
    id: "soundings",
    name: "Soundings",
    url: "https://www.soundingsonline.com",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.soundingsonline.com/.rss/full/", "https://www.soundingsonline.com"],
    focus: "Boating stories, seamanship, boat ownership, cruising, people and marine culture.",
    sections: ["News", "Lifestyle", "Destinations", "Masterclass"],
  }),
  source({
    id: "passagemaker",
    name: "PassageMaker",
    url: "https://www.passagemaker.com",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.passagemaker.com/.rss/full/", "https://www.passagemaker.com"],
    focus: "Trawlers, passagemaking, boat reviews, gear, long-range cruising and ownership.",
    sections: ["Reviews", "Destinations", "Gear", "Masterclass"],
  }),
  source({
    id: "sail-magazine",
    name: "Sail Magazine",
    url: "https://www.sailmagazine.com",
    group: "Cruising, ports and lifestyle",
    feedUrls: ["https://www.sailmagazine.com/.rss/full/", "https://www.sailmagazine.com"],
    focus: "Sailing news, cruising, gear, technique, boat tests and lifestyle afloat.",
    sections: ["News", "Reviews", "Gear", "Destinations", "Masterclass"],
  }),
];
