import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const stories = sqliteTable("stories", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  category: text("category").notNull(),
  sectionSlugsJson: text("section_slugs_json").notNull().default("[]"),
  date: text("date").notNull(),
  author: text("author").notNull(),
  sourceType: text("source_type").notNull(),
  sourceName: text("source_name").notNull(),
  sourceUrl: text("source_url"),
  originalSourceType: text("original_source_type").notNull().default(""),
  originalSourceRef: text("original_source_ref").notNull().default(""),
  originalSourceContent: text("original_source_content").notNull().default(""),
  imageUrl: text("image_url").notNull(),
  imageAlt: text("image_alt").notNull(),
  imageCredit: text("image_credit").notNull().default(""),
  imageCaption: text("image_caption").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  videoCaption: text("video_caption").notNull().default(""),
  videoPosition: text("video_position").notNull().default(""),
  oldSeaDogsView: text("old_sea_dogs_view").notNull().default(""),
  sourceNotes: text("source_notes").notNull().default(""),
  methodNotes: text("method_notes").notNull().default(""),
  contentBasis: text("content_basis").notNull().default(""),
  editorialStatus: text("editorial_status").notNull().default("Needs improvement"),
  noindex: integer("noindex", { mode: "boolean" }).notNull().default(false),
  summary: text("summary").notNull(),
  bodyJson: text("body_json").notNull(),
  tagsJson: text("tags_json").notNull(),
  readMinutes: integer("read_minutes").notNull(),
  isFeatured: integer("is_featured", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("published"),
  publishedAt: text("published_at").notNull().default(""),
  scheduledPublishAt: text("scheduled_publish_at").notNull().default(""),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const storyStatusHistory = sqliteTable("story_status_history", {
  id: text("id").primaryKey(),
  storyId: text("story_id").notNull(),
  fromStatus: text("from_status").notNull().default(""),
  toStatus: text("to_status").notNull(),
  fromWorkflow: text("from_workflow").notNull().default(""),
  toWorkflow: text("to_workflow").notNull().default(""),
  changedBy: text("changed_by").notNull().default("Bridge editor"),
  changedAt: text("changed_at").notNull(),
});

export const storyRevisions = sqliteTable("story_revisions", {
  id: text("id").primaryKey(),
  storyId: text("story_id").notNull(),
  snapshotJson: text("snapshot_json").notNull(),
  reason: text("reason").notNull().default("Published story edit"),
  createdBy: text("created_by").notNull().default("Bridge editor"),
  createdAt: text("created_at").notNull(),
});

export const mediaAssets = sqliteTable("media_assets", {
  id: text("id").primaryKey(),
  filename: text("filename").notNull(),
  originalFilename: text("original_filename").notNull().default(""),
  displayName: text("display_name").notNull().default(""),
  internalTitle: text("internal_title").notNull().default(""),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  r2Key: text("r2_key").notNull(),
  url: text("url").notNull(),
  alt: text("alt").notNull().default(""),
  caption: text("caption").notNull().default(""),
  credit: text("credit").notNull().default(""),
  copyright: text("copyright").notNull().default(""),
  copyrightOwnership: text("copyright_ownership").notNull().default("unknown"),
  copyrightOwner: text("copyright_owner").notNull().default(""),
  photographer: text("photographer").notNull().default(""),
  source: text("source").notNull().default(""),
  licence: text("licence").notNull().default(""),
  permissionNote: text("permission_note").notNull().default(""),
  usageRestrictions: text("usage_restrictions").notNull().default(""),
  creditLine: text("credit_line").notNull().default(""),
  permissionReceivedAt: text("permission_received_at").notNull().default(""),
  location: text("location").notNull().default(""),
  dateTaken: text("date_taken").notNull().default(""),
  sourceType: text("source_type").notNull().default("upload"),
  category: text("category").notNull().default(""),
  tagsJson: text("tags_json").notNull().default("[]"),
  collectionsJson: text("collections_json").notNull().default("[]"),
  storyIdsJson: text("story_ids_json").notNull().default("[]"),
  galleryItemId: text("gallery_item_id").notNull().default(""),
  originalKey: text("original_key").notNull().default(""),
  webKey: text("web_key").notNull().default(""),
  width: integer("width").notNull().default(0),
  height: integer("height").notNull().default(0),
  posterMediaId: text("poster_media_id").notNull().default(""),
  externalUrl: text("external_url").notNull().default(""),
  description: text("description").notNull().default(""),
  storyAssociationId: text("story_association_id").notNull().default(""),
  galleryAssociationId: text("gallery_association_id").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

export const galleryCategories = sqliteTable("gallery_categories", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description").notNull().default(""),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const galleryItems = sqliteTable("gallery_items", {
  id: text("id").primaryKey(),
  mediaId: text("media_id").notNull(),
  sourceType: text("source_type").notNull().default("upload"),
  sourceId: text("source_id").notNull().default(""),
  sourceUrl: text("source_url").notNull().default(""),
  title: text("title").notNull().default(""),
  caption: text("caption").notNull().default(""),
  alt: text("alt").notNull().default(""),
  credit: text("credit").notNull().default(""),
  copyright: text("copyright").notNull().default(""),
  location: text("location").notNull().default(""),
  dateTaken: text("date_taken").notNull().default(""),
  tagsJson: text("tags_json").notNull().default("[]"),
  categoryIdsJson: text("category_ids_json").notNull().default("[]"),
  storyIdsJson: text("story_ids_json").notNull().default("[]"),
  boatId: text("boat_id").notNull().default(""),
  marinaId: text("marina_id").notNull().default(""),
  yachtClubId: text("yacht_club_id").notNull().default(""),
  eventId: text("event_id").notNull().default(""),
  status: text("status").notNull().default("pending"),
  rejectionReason: text("rejection_reason").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const instagramImports = sqliteTable("instagram_imports", {
  id: text("id").primaryKey(),
  instagramMediaId: text("instagram_media_id").notNull().unique(),
  permalink: text("permalink").notNull().default(""),
  mediaType: text("media_type").notNull().default("IMAGE"),
  caption: text("caption").notNull().default(""),
  timestamp: text("timestamp").notNull().default(""),
  mediaId: text("media_id").notNull().default(""),
  galleryItemId: text("gallery_item_id").notNull().default(""),
  status: text("status").notNull().default("pending"),
  importedAt: text("imported_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const ads = sqliteTable("ads", {
  id: text("id").primaryKey(),
  placement: text("placement").notNull(),
  kind: text("kind").notNull().default("manual"),
  label: text("label").notNull(),
  title: text("title").notNull().default(""),
  body: text("body").notNull().default(""),
  imageUrl: text("image_url").notNull().default(""),
  linkUrl: text("link_url").notNull().default(""),
  code: text("code").notNull().default(""),
  startDate: text("start_date").notNull().default(""),
  endDate: text("end_date").notNull().default(""),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const siteSettings = sqliteTable("site_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const socialEvents = sqliteTable("social_events", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  platform: text("platform").notNull().default(""),
  target: text("target").notNull().default(""),
  storySlug: text("story_slug").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

export const pressReleaseEmails = sqliteTable("press_release_emails", {
  id: text("id").primaryKey(),
  messageId: text("message_id").notNull().default(""),
  senderName: text("sender_name").notNull().default(""),
  senderEmail: text("sender_email").notNull().default(""),
  senderDomain: text("sender_domain").notNull().default(""),
  subject: text("subject").notNull(),
  receivedAt: text("received_at").notNull(),
  preview: text("preview").notNull().default(""),
  bodyText: text("body_text").notNull().default(""),
  rawEmail: text("raw_email").notNull().default(""),
  attachmentsJson: text("attachments_json").notNull().default("[]"),
  status: text("status").notNull().default("new"),
  category: text("category").notNull().default("News"),
  relevanceScore: integer("relevance_score").notNull().default(0),
  duplicateOf: text("duplicate_of").notNull().default(""),
  duplicateScore: integer("duplicate_score").notNull().default(0),
  warningsJson: text("warnings_json").notNull().default("[]"),
  generatedTitle: text("generated_title").notNull().default(""),
  generatedExcerpt: text("generated_excerpt").notNull().default(""),
  generatedBodyJson: text("generated_body_json").notNull().default("[]"),
  generatedWordCount: integer("generated_word_count").notNull().default(0),
  selectedAttachmentId: text("selected_attachment_id").notNull().default(""),
  imageUrl: text("image_url").notNull().default(""),
  imageAlt: text("image_alt").notNull().default(""),
  imageCredit: text("image_credit").notNull().default(""),
  imageCaption: text("image_caption").notNull().default(""),
  rightsNote: text("rights_note").notNull().default(""),
  storyId: text("story_id").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const pressReleaseBlockedSenders = sqliteTable("press_release_blocked_senders", {
  id: text("id").primaryKey(),
  value: text("value").notNull(),
  kind: text("kind").notNull().default("sender"),
  reason: text("reason").notNull().default(""),
  createdAt: text("created_at").notNull(),
});
